### ISSUE TITLE
I am interested in this application 

### ISSUE THREAD

**Issue by demianrey** [losgif/sail#3]
it is possible to have a VPN application that communicates with the panel

**Comment by losgif** [comment]
Yes, you can do it yourself. This project is just a demo.

**Comment by ogbeh** [comment]
I have managed to get it to run,  do you have any idea on how to fetch data from v2baord?

**Comment by losgif** [comment]
as far as I know v2borad api's response as json data

**Comment by demianrey** [comment]
I think that several of us need the complete application with the xray or v2ray core and that it communicates with the sspanel and v2board panels, we can make a donation so that they can finish the project, what do you think?

**Comment by ChristianSwift** [comment]
草，逼上梁山

**Comment by ogbeh** [comment]
> I think that several of us need the complete application with the xray or v2ray core and that it communicates with the sspanel and v2board panels, we can make a donation so that they can finish the project, what do you think?

sounds like a good idea, I have gotten the app to run on android and I have modified it to english but I cant get it to fetch user data from v2board backend

**Comment by carzygod** [comment]
Please , help us to build it into an peer to peer type Dapp  . which might help it much more save

**Comment by ChristianSwift** [comment]
> Please , help us to build it into an peer to peer type Dapp . which might help it much more save

？

**Comment by demianrey** [comment]
> > I think that several of us need the complete application with the xray or v2ray core and that it communicates with the sspanel and v2board panels, we can make a donation so that they can finish the project, what do you think?
> 
> sounds like a good idea, I have gotten the app to run on android and I have modified it to english but I cant get it to fetch user data from v2board backend

I haven't tried to compile yet, but honestly my programming is very basic... I'm going to review hoping to achieve something, hopefully the developers are interested in making this project functional, I repeat, I could donate some money hehe

**Comment by sdjnpoi** [comment]
我先是修改了基础接口地址，对接了v2board后端。我测试时发现，登录的密码错误或者其他不会有反馈。然后在订阅套餐会有：type 'int' is not a subtype of type 'double' 在  选择连接节点有：Invalid argument(s): The source must not be null的报错，不知道是不是我配置问题，或者框架版本问题。希望开发人员继续优惠，如果可以捐助一下也可以

**Comment by demianrey** [comment]
> 

How did you compile, I can't

**Comment by losgif** [comment]
> 我先是修改了基础接口地址，对接了v2board后端。我测试时发现，登录的密码错误或者其他不会有反馈。然后在订阅套餐会有：type 'int' is not a subtype of type 'double' 在 选择连接节点有：Invalid argument(s): The source must not be null的报错，不知道是不是我配置问题，或者框架版本问题。希望开发人员继续优惠，如果可以捐助一下也可以

It has been fixed, just update the code.

**Comment by sdjnpoi** [comment]
> 

demo里vpn的连接的功能是正常的吗(Android&Ios)

**Comment by sdjnpoi** [comment]
![QQ图片20220616144019](https://user-images.githubusercontent.com/94992441/174007873-6acd05f0-64af-4afd-8746-0022cca2eb93.jpg)
![QQ图片20220616144025](https://user-images.githubusercontent.com/94992441/174007880-22adbdbc-1c0e-4b63-9586-6c29c5dc088a.jpg)
谢谢，登录时输入错误的账号密码没有反馈提示
![QQ截图20220616144322](https://user-images.githubusercontent.com/94992441/174008218-37ed08dd-acdb-44c9-8902-e377dc76e654.jpg)

**Comment by sdjnpoi** [comment]
您用的flutter是多少版本

**Comment by demianrey** [comment]
> 您用的flutter是多少版本

Can you help me compile, I tried it on Windows via cmd and with the Flutter plugin in Android Studio, without success

**Comment by sdjnpoi** [comment]
> 

可以我需要怎么找到你？留下你的方式

**Comment by demianrey** [comment]
> 

TG @demianrey

**Comment by zhang757396194** [comment]
***@***.***

------------------ Original ------------------
From: sdjnpoi ***@***.***&gt;
Date: Fri,Jun 17,2022 7:33 AM
To: losgif/sail ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [losgif/sail] I am interested in this application  (Issue #3)





   
可以我需要怎么找到你？留下你的方式

**Comment by zhang757396194** [comment]
1.5.6
------------------ Original ------------------
From: demianrey ***@***.***&gt;
Date: Fri,Jun 17,2022 2:03 AM
To: losgif/sail ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [losgif/sail] I am interested in this application  (Issue #3)





  
您用的flutter是多少版本
  
Can you help me compile, I tried it on Windows via cmd and with the Flutter plugin in Android Studio, without success

**Comment by zhang757396194** [comment]
为什么不去看看官方文档呢
------------------ Original ------------------
From: sdjnpoi ***@***.***&gt;
Date: Thu,Jun 16,2022 2:43 PM
To: losgif/sail ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [losgif/sail] I am interested in this application  (Issue #3)





 

 
 谢谢，登录时输入错误的账号密码没有反馈提示

**Comment by sdjnpoi** [comment]
> 1.5.6 ------------------ 原创 ------------------ 来自：demianrey ***@*** .***> 日期：2022 年 6 月 17 日星期五 2:03 AM 收件人：losgif/sail ***@***.***> 抄送：已订阅 ***@***.***> Subject: Re: [losgif/sail] 我对这个应用很感兴趣(Issue #3 ) 你用的flutter是多少版本你能帮我编译一下吗，我在windows上通过cmd和android studio中的flutter插件试过了，没有成功 — 直接回复此电子邮件、在 GitHub 上查看或取消订阅。您收到此消息是因为您订阅了此线程。消息 ID：***@***.***>



> 编译没问题的，您是编译报错了吗？

**Comment by zhang757396194** [comment]
1.5.6
------------------ Original ------------------
From: sdjnpoi ***@***.***&gt;
Date: Fri,Jun 17,2022 2:06 PM
To: losgif/sail ***@***.***&gt;
Cc: zhang757396194 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [losgif/sail] I am interested in this application  (Issue #3)

**Comment by sdjnpoi** [comment]
東西越來越好了，目前遇到了一個新問題，在網絡不是很穩定的情況下，請求接口會不是很穩定，Debug雖然會顯示：請求錯誤。APP會一直保持登錄轉圈圈的狀態，可以加一下請求錯誤相關的判斷。

**Comment by losgif** [comment]
> 東西越來越好了，目前遇到了一個新問題，在網絡不是很穩定的情況下，請求接口會不是很穩定，Debug雖然會顯示：請求錯誤。APP會一直保持登錄轉圈圈的狀態，可以加一下請求錯誤相關的判斷。

安排

**Comment by ogbeh** [comment]
> > Things are getting better and better. At present, I have encountered a new problem. When the network is not very stable, the request interface will not be very stable. Although Debug will display: Request error. The APP will always keep the status of logging in and circling, and you can add judgments related to request errors.
> 
> arrange

Thanks a lot for your effort.

**Comment by sdjnpoi** [comment]
作者，最新更新的小部件顯示什麽功能的實現方式

**Comment by zhang757396194** [comment]
仔细看介绍

------------------ Original ------------------
From: sdjnpoi ***@***.***&gt;
Date: Fri,Jun 24,2022 8:15 AM
To: losgif/sail ***@***.***&gt;
Cc: zhang757396194 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [losgif/sail] I am interested in this application  (Issue #3)





 
作者，最新更新的小部件顯示什麽功能的實現方式

**Comment by sdjnpoi** [comment]
發現了一些UI操作的小優化，例如點擊選擇鏈接節點可以直接跳到節點列表裏面，儅選擇完節點后可以跳到首頁裏面，ping可以進入節點列表時自動測，在您項目中的v2board面板，其中KH柬埔寨01綫路有UI方面錯誤提示，節點聊列表的每個節點模塊的顯示可以寬一些。在購買方面使用alipay:// 無法喚醒支付寶進行支付。無法調用第三方的支付  {安卓測試}

**Comment by sdjnpoi** [comment]
好像无法获取到节点列表

**Comment by sdjnpoi** [comment]
dns。github。bet，可能是他面板有问题了，获取不到节点了

**Comment by losgif** [comment]
> 發現了一些UI操作的小優化，例如點擊選擇鏈接節點可以直接跳到節點列表裏面，儅選擇完節點后可以跳到首頁裏面，ping可以進入節點列表時自動測，在您項目中的v2board面板，其中KH柬埔寨01綫路有UI方面錯誤提示，節點聊列表的每個節點模塊的顯示可以寬一些。在購買方面使用alipay:// 無法喚醒支付寶進行支付。無法調用第三方的支付 {安卓測試}

可以单独提issue, 这个issue可以关闭了
