### ISSUE TITLE
v2board 要怎么对接呢大佬

### ISSUE THREAD

**Issue by nrsxs** [losgif/sail#4]
rt

**Comment by losgif** [comment]
修改后端API地址
https://github.com/losgif/sail/blob/9d5810a48d1b4aab7bc6e4e4d94197db26b9943e/lib/constant/app_urls.dart#L2

**Comment by zhang757396194** [comment]
参考官方文档

------------------ 原始邮件 ------------------
发件人: losgif ***@***.***&gt;
发送时间: 2022年6月17日 08:49
收件人: losgif/sail ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[losgif/sail] v2board 要怎么对接呢大佬 (Issue #4)





 
Closed #4 as completed.
