### ISSUE TITLE
大佬，你这个demoFlutter版本是多少

### ISSUE THREAD

**Issue by tzt1994** [losgif/sail#5]

**Comment by losgif** [comment]
<img width="541" alt="image" src="https://user-images.githubusercontent.com/13404752/174199817-365349ac-2374-4e8b-9d1a-434b0900bc49.png">
v3.0.1

**Comment by zhang757396194** [comment]
版本是1.5.6

------------------ 原始邮件 ------------------
发件人: losgif ***@***.***&gt;
发送时间: 2022年6月17日 08:49
收件人: losgif/sail ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[losgif/sail] 大佬，你这个demoFlutter版本是多少 (Issue #5)





 
Closed #5 as completed.

**Comment by zhang757396194** [comment]
1.5.6
------------------ 原始邮件 ------------------
发件人: tzt_Han ***@***.***&gt;
发送时间: 2022年6月16日 15:52
收件人: losgif/sail ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[losgif/sail] 大佬，你这个demoFlutter版本是多少 (Issue #5)
