### ISSUE TITLE
付费解决问题

### ISSUE THREAD

**Issue by IOCloudFly** [losgif/sail#52]
有谁运行起来了，方便给个联系方式吗，或者加我的v :13718004099

**Comment by ghost** [comment]
我只有iOS的？有telegram吗？我可以给你demo

**Comment by IOCloudFly** [comment]
没有那个，我登录不上去



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月23日 22:57 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [sail-tunnel/sail] 付费解决问题 (Issue #52) |

我只有iOS的？有telegram吗？我可以给你demo

**Comment by ghost** [comment]
你没有翻墙软件吗？比如shadowrocket？

**Comment by ghost** [comment]
或者你给个邮箱，我把源码发你好了

**Comment by IOCloudFly** [comment]
***@***.***



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月23日 23:13 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [sail-tunnel/sail] 付费解决问题 (Issue #52) |

或者你给个邮箱，我把源码发你好了

**Comment by ghost** [comment]
你这乱码，我能看到啥，哭了呀，不过你打算出多少钱

**Comment by launchpool1** [comment]
Skype: live:.cid.8348de65da727437

**Comment by IOCloudFly** [comment]
> 你这乱码，我能看到啥，哭了呀，不过你打算出多少钱

有没有android版本的，1147235807@qq.com

**Comment by ghost** [comment]
没有，安卓版本你随便找，一大堆

**Comment by IOCloudFly** [comment]
找了几个都不能用



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月25日 23:56 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [sail-tunnel/sail] 付费解决问题 (Issue #52) |

没有，安卓版本你随便找，一大堆

**Comment by ghost** [comment]
那就帮不了了

**Comment by MindarkTest** [comment]
> 我只有iOS的？有telegram吗？我可以给你demo

嗨您好，请问我可以要一下demo和代码吗？ 想问一下您的demo可以使用vpn功能吗，我这边代码跑起来了，但是一直在 `_appModel.setConfigProxies(_userModel, _serverModel); `这边遇到问题。用Xcode跑，他持续报错以下错误
<img width="545" alt="截屏2024-05-01 下午3 38 38" src="https://github.com/sail-tunnel/sail/assets/166595658/e5d5607e-23dc-4865-b0f0-e671c29cb1a8">

我目前是ios新手，最近因为需要做ios的软件，这个是我第一次打开开发的软件，可能对ios开发不太了解。希望能见谅，谢谢。

**Comment by ghost** [comment]
需要付费购买的哈，如果需要就留下邮箱吧

**Comment by MindarkTest** [comment]
> 需要付费购买的哈，如果需要就留下邮箱吧

好的，mindarktest@gmail.com

**Comment by ghost** [comment]
邮箱沟通吧

**Comment by 13582351091** [comment]
t.me/Lcfstar
实现效果https://wwf.lanzoue.com/b03fnqqla
希望愿意交流的来，windows和macos的弄好后还没搞ios端给我开发者账号封了我去，有老哥愿意提供帮助一起促进这个项目吗
